# Usa uma imagem slim do python para manter o container leve
FROM python:3.11-slim

# Impede que o Python gere arquivos .pyc e permite logs em tempo real

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNFFERED 1

# Instala dependências do sistema necessárias para bibliotecas de IA e Postgres
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Instala as dependências do Python
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copia o restante do projeto
COPY . /app/

# Expõe a porta que o Django usa
EXPOSE 8000