# Generated by Django 5.2.1 on 2026-02-26 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='livros/'),
        ),
    ]
